In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
df = pd.read_csv("datasets/covid_philippines.csv")

In [3]:
df.head()

Unnamed: 0     video_id                                        video_title  \
0           0  m3P-bmt3Uqw    JN.1 COVID-19 subvariant causing spike in cases   
1           1  sYI97jv-pZg  PH records 2,725 new COVID cases from Dec. 12 ...   
2           2  3YFpjgIQqEo  WATCH: DOH Usec. Tayag on rise of COVID-19 cas...   
3           3  CEIrzjA8euQ  DOH urges public to mask up amid rise in COVID...   
4           4  DWxIvQlpJK8  Metro Manila to be placed on lockdown due to c...   

                                         description   video_dop  view_count  \
0  'An infectious disease expert says the new COV...  2023-12-25        6495   
1  'The World Tonight: The daily average of the P...  2023-12-18        1982   
2  'Dateline Philippines: Karmina Constantino tal...  2023-12-07        9354   
3  'Dateline Philippines: The Philippine Health D...  2023-12-13        2010   
4  'Subscribe: https://www.youtube.com/@Rappler/\...  2020-03-12      104353   

   like_count  comment_count                channel_id    channel_title  \
0          45             18  UCj6spMO3ybZPobE0T5perHA  CNN Philippines   
1          14              3  UCvi6hEzLM-Z_unKPSuuzKvg         ANC 24/7   
2          80             17  UCvi6hEzLM-Z_unKPSuuzKvg         ANC 24/7   
3          26              2  UCvi6hEzLM-Z_unKPSuuzKvg         ANC 24/7   
4         736             18  UCdnZdQxYXnbN4uWJg96oGxw          Rappler   

  channel_dop  sub_count  total_videos  
0  2015-03-16    1390000         22741  
1  2010-01-29    1500000         70077  
2  2010-01-29    1500000         70077  
3  2010-01-29    1500000         70077  
4  2011-12-02    1930000         50275

In [4]:
df[['like_count', 'comment_count']].describe()

like_count  comment_count
count    400.000000     400.000000
mean     521.247500     190.087500
std     1376.627755     599.679363
min        2.000000       0.000000
25%       61.500000      11.000000
50%      153.000000      46.000000
75%      431.750000     155.500000
max    12843.000000    6508.000000

In [5]:
view_count = np.array(df['view_count'])
like_count = np.array(df['like_count'])
comment_count = np.array(df['comment_count'])

In [7]:
view_count

array([   6495,    1982,    9354,    2010,  104353,   14611,   12783,
          1183,  323101,   37964,     898,   33950,    4447,   90431,
         17959,    2340,     606,  156448,   37156,   34707,  127589,
        436724,  178976, 1516457,  239819,   40201,  150638,  141140,
         91261,  142751,  130344,   24702,    2462,   24864,   23581,
          2186,   77308,    6918,  494024, 1330178,  185129,  120766,
         71000,   73177,   33362,   23691,  344835,  436660,   24821,
          3289,   16829,  144724,   53088,   26404,    1363,  203783,
         16227,   20932,   92406,   21335,  193339,   29726,   38471,
         87389,  251651,  201877,   38755,   16960, 1362590,   42293,
         60285,  111908,   17148,   11692,   88102,   63646,    7723,
          1522,   47610,   30967,   37017,    6192,   50683,  129655,
          5841,    5472,   18082,   14689,   24251,   89352,  183838,
         85761,    5452,  102905,    2584,   31578,  105205,  409742,
          3130,   27

In [8]:
like_count

array([   45,    14,    80,    26,   736,    87,    66,    10,  3283,
          86,     8,   476,    41,   712,   100,    19,    14,  2174,
         304,   365,   906,  2769,   947, 10482,   976,   352,   511,
        1337,   545,   658,   257,   111,    27,   212,   155,     9,
        1298,   119,  3302, 12843,   895,   381,   468,   318,   187,
          78,  1951,  4893,   153,    25,   111,  1546,   304,   328,
          17,  1096,   300,   153,   538,   419,  2030,   194,   493,
         143,  2346,  1397,    75,    91,  2907,   257,  1683,   274,
         263,    67,   168,   132,    72,    29,   531,   327,   169,
          58,   602,  1286,    21,    37,   249,   173,   235,   339,
        2336,   198,    45,   429,     8,   516,   220,  1980,    28,
         316,   316,   229,     4,   339,   342,    67,  1286,     5,
          80,     8,    58,    16,   429,  1148,    44,   250,   506,
          28,   380,     4,  8806,   102,  1980,   694,    13,   119,
         672,    45,

In [6]:
comment_count

array([  18,    3,   17,    2,   18,   25,   30,    3,  619,   81,    4,
        131,   17,   87,   80,   10,    3, 1080,   95,  168,  532, 1369,
        417,  948,  389,  166,   15,  435, 1313,  112,  186,   66,    3,
         94,   22,   12,  705,   26,    0, 6508,  286,    0,  112,   58,
         11,   53,    0, 1289,   58,    4,   70, 1041,  282,   41,    0,
        550,   30,   32,  211,  174,  815,  157,  132,   72, 1184,  516,
          5,   32,  230,   93,   45,  152,   94,    7,    0,    0,   15,
          5,  474,  601,   52,   16,  135, 1344,   34,    5,  157,   41,
        115,  174,  403,  155,   31,  116,    2,  338,    0,  196,    1,
        173,  173,    1,    1,  174,    0,   94, 1344,   10,    1,    0,
         36,   13,  116,  319,   13,    0,  601,    1,  157,    0, 3149,
         31,  196,    2,    9,   69,  266,   27,   46,   62,  703,    5,
         33,  155, 1019,   22,   14,   94,   38,   61,    0, 1045,  168,
          9,   36,  367, 1820,   17,    5,    0,  2

In [9]:
norm_view_count = preprocessing.normalize([view_count])[0]
norm_like_count = preprocessing.normalize([like_count])[0]
norm_comment_count = preprocessing.normalize([comment_count])[0]